version: "3.9"

services:
    client:
        container_name: client_react_c
        build:
            context: ./
            dockerfile: ./frontend/client/Dockerfile        
        restart: on-failure
        ports:
            - "3000:3000"
        volumes:
            - ./frontend/client:/app
            - /app/node_modules
        networks:
            - microservice
        environment:
            - CHOKIDAR_USEPOLLING=true
        depends_on:
            - auth_service
            - profiles_service                         
    
    auth_service:
        container_name: auth_service_c        
        build:
            context: ./
            dockerfile: ./auth_service/Dockerfile
        command: ./start_django
        volumes:
            - ./auth_service:/app
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        ports:
            - "8002:8002"       
        env_file:
            - .env              
        networks:
            - microservice
        depends_on:
            - mysql_db
    
    profiles_service:
        container_name: profiles_service_c        
        build:
            context: ./
            dockerfile: ./profiles_service/Dockerfile
        command: ./start_django
        volumes:
            - ./profiles_service:/app
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        ports:
            - "8003:8003"        
        env_file:
            - .env              
        networks:
            - microservice
        depends_on:
            - mysql_db  
             
    mysql_db:
        container_name: mysql_db_c
        restart: always
        image: mysql:5.7.22
        command: --init-file /data/application/init.sql                     
        environment:
            #MYSQL_DATABASE: profile
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            #- ./db/init/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./db/init/init.sql:/data/application/init.sql
            - ./db/dbdata:/var/lib/mysql
        ports:
            - "3306:3306"    
        networks:
            - microservice
    
            
networks:
    microservice:
        driver: bridge 
                
volumes:
    static_volume:
    media_volume:
