#!/bin/bash

set -o errexit

set -o pipefail

set -o nounset

input="hello"
mysql_ready() {
python << END

import mysql.connector
from mysql.connector import errorcode
import sys
import os
from pathlib import Path
import environ

env = environ.Env(DEBUG=(bool, False))
CURRENT_DIR = Path(__file__).resolve().parent
environ.Env.read_env(CURRENT_DIR / ".env")

cwd = os.environ['PWD']
print("cwd is: " + cwd)
print("$input world")

try:    
    mysql.connector.connect(
        host=env('MYSQL_HOST_CLIENT'),
        database=env('MYSQL_DATABASE_CLIENT'),
        user=env('MYSQL_USER'),
        password=env('MYSQL_PASSWORD'),     
        port=env('MYSQL_PORT_CLIENT'),        
        ssl_disabled=True             
    )
except mysql.connector.Error as err:
    if err.errno == errorcode.ER_ACCESS_DENIED_ERROR:
        print("db user name or password are invalid")
    elif err.errno == errorcode.ER_BAD_DB_ERROR:        
        print("Database does not exist")
    else:
        print(err)        
    sys.exit(-1)
sys.exit(0)
print("connection is successful")

END
}

until mysql_ready; do
 >&2 echo "MySql connection is in progress."
 sleep 1 
done
>&1 echo "MySql connection is successful."
sleep 10
exec "$@"

