# Generated by Django 3.2.7 on 2023-06-12 18:56

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='Username')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default=None, max_length=30, region=None, verbose_name='Phone Number')),
                ('profile_photo', models.ImageField(default='/default.jpg', upload_to='', verbose_name='Photo')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='O', max_length=1, verbose_name='Gender')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
            ],
        ),
    ]
