# Generated by Django 3.2.7 on 2023-06-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profiles_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='id',
        ),
        migrations.AlterField(
            model_name='profiles',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
