version: "3.9"

services:
    profiles_service:
        container_name: profiles_service_c
        build:
            context: .
            dockerfile: ./Dockerfile
        command: ./start_django
        volumes:
            - .:/app
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        ports:
            - "8003:8003"
        env_file:
            - .env
        networks:
            - microservice    

networks:
    microservice:
        driver: bridge

volumes:
    static_volume:
    media_volume:
